"""initialize and create User, User Payment, User Adress, Reservation, Account, Service Category, Service, User Service databases

Revision ID: ff73a94310e0
Revises: 95ac27545109
Create Date: 2025-03-06 02:07:39.950295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff73a94310e0'
down_revision: Union[str, None] = '95ac27545109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
