"""add details column on UserService for price and duration

Revision ID: 00886c24c48b
Revises: 64b894143d0c
Create Date: 2025-03-07 18:22:01.660703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00886c24c48b'
down_revision: Union[str, None] = '64b894143d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_services', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_services', 'details')
    # ### end Alembic commands ###
