"""remove the relationship between service and service category, create parenting pattern

Revision ID: 5e36900e222e
Revises: 657be15dbd5a
Create Date: 2025-03-07 18:11:42.192703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e36900e222e'
down_revision: Union[str, None] = '657be15dbd5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
