"""remove the relationship between service and service category, create parenting pattern

Revision ID: 793e2880546d
Revises: a91cc9fbdebb
Create Date: 2025-03-07 18:01:49.043429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '793e2880546d'
down_revision: Union[str, None] = 'a91cc9fbdebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('parent_service_id', sa.BigInteger(), nullable=True))
    op.add_column('services', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.alter_column('services', 'service_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint('services_service_category_id_fkey', 'services', type_='foreignkey')
    op.create_foreign_key(None, 'services', 'services', ['parent_service_id'], ['service_id'])
    op.drop_column('services', 'service_category_id')
    op.drop_column('services', 'detail')
    op.alter_column('user_services', 'service_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_services', 'service_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.add_column('services', sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('services', sa.Column('service_category_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.create_foreign_key('services_service_category_id_fkey', 'services', 'service_categories', ['service_category_id'], ['service_category_id'])
    op.alter_column('services', 'service_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('services', 'details')
    op.drop_column('services', 'parent_service_id')
    # ### end Alembic commands ###
