"""indexing primary keys

Revision ID: 3063db808657
Revises: 8b00251e8401
Create Date: 2025-03-29 14:23:52.698458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3063db808657'
down_revision: Union[str, None] = '8b00251e8401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_public_id'), 'accounts', ['public_id'], unique=False)
    op.drop_constraint('reservations_public_id_key', 'reservations', type_='unique')
    op.create_index(op.f('ix_reservations_id'), 'reservations', ['id'], unique=False)
    op.create_index(op.f('ix_reservations_public_id'), 'reservations', ['public_id'], unique=True)
    op.drop_constraint('services_public_id_key', 'services', type_='unique')
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_services_public_id'), 'services', ['public_id'], unique=True)
    op.drop_constraint('user_addresses_public_id_key', 'user_addresses', type_='unique')
    op.create_index(op.f('ix_user_addresses_id'), 'user_addresses', ['id'], unique=False)
    op.create_index(op.f('ix_user_addresses_public_id'), 'user_addresses', ['public_id'], unique=True)
    op.drop_constraint('user_payments_ref_id_key', 'user_payments', type_='unique')
    op.create_index(op.f('ix_user_payments_id'), 'user_payments', ['id'], unique=False)
    op.create_index(op.f('ix_user_payments_ref_id'), 'user_payments', ['ref_id'], unique=True)
    op.drop_constraint('user_services_public_id_key', 'user_services', type_='unique')
    op.create_index(op.f('ix_user_services_id'), 'user_services', ['id'], unique=False)
    op.create_index(op.f('ix_user_services_public_id'), 'user_services', ['public_id'], unique=True)
    op.drop_constraint('users_public_id_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint('users_public_id_key', 'users', ['public_id'])
    op.drop_index(op.f('ix_user_services_public_id'), table_name='user_services')
    op.drop_index(op.f('ix_user_services_id'), table_name='user_services')
    op.create_unique_constraint('user_services_public_id_key', 'user_services', ['public_id'])
    op.drop_index(op.f('ix_user_payments_ref_id'), table_name='user_payments')
    op.drop_index(op.f('ix_user_payments_id'), table_name='user_payments')
    op.create_unique_constraint('user_payments_ref_id_key', 'user_payments', ['ref_id'])
    op.drop_index(op.f('ix_user_addresses_public_id'), table_name='user_addresses')
    op.drop_index(op.f('ix_user_addresses_id'), table_name='user_addresses')
    op.create_unique_constraint('user_addresses_public_id_key', 'user_addresses', ['public_id'])
    op.drop_index(op.f('ix_services_public_id'), table_name='services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.create_unique_constraint('services_public_id_key', 'services', ['public_id'])
    op.drop_index(op.f('ix_reservations_public_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_id'), table_name='reservations')
    op.create_unique_constraint('reservations_public_id_key', 'reservations', ['public_id'])
    op.drop_index(op.f('ix_accounts_public_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    # ### end Alembic commands ###
